name: Generate GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Poorvi-tech
          template: classic
          base: header, activity, community, repositories, metadata
          config_commits: yes
          config_issues: yes
          config_prs: yes
          config_repositories: yes
          config_stargazers: yes
          config_followers: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_recent_days: 30
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_languages: yes
          plugin_traffic: yes
          plugin_traffic_percentage: yes
          plugin_traffic_days: 14
          plugin_notable: yes
          plugin_notable_repositories: auto
          plugin_notable_from: organization, user
          plugin_notable_indepth: yes
          plugin_notable_types: fork, public, private
          plugin_notable_factor: stars
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 24
          plugin_repositories: yes
          plugin_repositories_limit: 8
          plugin_repositories_sort: stars-desc
          plugin_repositories_affiliations: owner, collaborator, organization_member
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_discussions_limit: 8
          plugin_gists: yes
          plugin_lines: yes
          plugin_lines_repositories_limit: 4
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: date
          plugin_stargazers_limit: 4
          plugin_stargazers_repositories: auto
          plugin_followup: yes
          output_action: write
          filename: github-metrics.svg
